services:
  nginx:
    container_name: nginx
    build: containers/nginx
    ports:
      - "8080:443"
    restart: always
    depends_on:
      - backend
  db:
    container_name: postgres
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    ports:
      - '5432:5432'
  backend:
    container_name: backend
    build: ./containers/backend/
    volumes:
      - ./containers/backend/app/:/usr/src/app/
    ports:
      - "8000:8000"
    env_file:
      - ./.env
volumes:
  postgres_data:

networks:
  django-network:
    driver: bridge