services:
  front-end:
    container_name: front-end
    build: services/front-end
    ports:
      - "8080:443"
    restart: always
    depends_on:
      - user-management
    networks:
      - network

  user-management:
    container_name: user-management
    build: ./services/user-management/
    expose:
      - "8000:8000"
    env_file: services/.env
    networks:
      - network

networks:
  network:
    driver: bridge
