services:
  front-end:
    container_name: front-end
    build: services/front-end
    ports:
      - "8080:443"
    restart: always
    depends_on:
      - user-management
    volumes:
      #- nginx:/singlepageapp
      - django:/tmp_static/
    networks:
      - network
    env_file:
      - .env
    entrypoint: sh -c "sh /entrypoint.sh"

  user-management:
    container_name: user-management
    build: ./services/user-management/
    expose:
      - "8000"
    volumes:
      - django:/singlepageapp
      - vault-token:/vault/token:ro
      - vault-ssl:/vault/ssl:ro
    networks:
      - network
    depends_on:
      - redis
    env_file:
      - .env

  chat:
    container_name: chat
    build: ./services/chat/
    expose:
      - "8001"
    volumes:
      - django:/singlepageapp/chat
    networks:
      - network
    depends_on:
      - redis
    env_file:
      - .env

  postgres:
    container_name: postgres
    build: ./services/postgres/
    env_file: .env
    expose:
      - "5432"
    networks:
     - network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  vault:
    build: ./services/vault/
    container_name: vault
    ports:
      - "8200:8200"
    cap_add:
      - IPC_LOCK
    env_file:
      - .env
    networks:
      - network
    healthcheck:
      test: ["CMD", "vault", "status"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
     - vault-data:/vault/data
     - vault-token:/vault/token
     - vault-ssl:/vault/ssl
    hostname: 'vault'
    environment:
      TZ: 'Europe/Paris'
      VAULT_SKIP_IP_AUTO_CONFIG: 'true'


  back-game:
    container_name: back-game-pong
    build: services/back-game-pong/
    expose:
      - "2605"
    env_file: .env
    networks:
     - network

  back-matchmaking:
    container_name: back-matchmaking-pong
    build: services/back-matchmaking-pong/
    expose:
      - "2607"
    env_file: .env
    networks:
      - network

  redis:
    container_name: redis
    build: ./services/redis/
    env_file: .env
    expose:
      - "6379"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - redis:/var/lib/redis
    networks:
      - network

networks:
  network:
    driver: bridge

volumes:
  nginx:
  django:
  vault-data:
  vault-token:
  vault-ssl:
  redis:
