
services:
  nginx:
    container_name: nginx
    build: ./containers/nginx
    ports:
      - "8080:443"
    restart: always
    depends_on:
      - backend
  db:
    container_name: postgres
    image: postgres:latest
    env_file:
      - ./containers/backend/conf/.env
    environment:
      - POSTGRES_USER=tasoeurenslip
      - POSTGRES_PASSWORD=tasoeurenslip
      - POSTGRES_DB=tasoeurenslip_db
  backend:
    container_name: backend
    build: ./containers/backend
    ports:
      - "8000:8000"
    env_file:
      - ./containers/backend/conf/.env