services:
  front-end:
    container_name: front-end
    build: services/front-end
    ports:
      - "8080:443"
    volumes:
      #- nginx:/singlepageapp
      - django:/tmp_static/
    networks:
      - network
    env_file:
      - .env
    entrypoint: sh -c "sh /entrypoint.sh"
    restart: on-failure

  pg-0:
    container_name: pg-0
    image: bitnami/postgresql-repmgr:14
    expose:
      - "5432"
    environment:
      - POSTGRESQL_POSTGRES_PASSWORD=custompassword
      - POSTGRESQL_USERNAME=customuser
      - POSTGRESQL_PASSWORD=custompassword
      - POSTGRESQL_DATABASE=postgres
      - REPMGR_PASSWORD=repmgrpassword
      - REPMGR_PRIMARY_HOST=pg-0
      - REPMGR_PARTNER_NODES=pg-0,pg-1
      - REPMGR_NODE_NAME=pg-0
      - REPMGR_NODE_NETWORK_NAME=pg-0
    networks:
      - network

  pg-1:
    container_name: pg-1
    image: bitnami/postgresql-repmgr:14
    expose:
      - "5432"
    environment:
      - POSTGRESQL_POSTGRES_PASSWORD=custompassword
      - POSTGRESQL_USERNAME=customuser
      - POSTGRESQL_PASSWORD=custompassword
      - POSTGRESQL_DATABASE=postgres
      - REPMGR_PASSWORD=repmgrpassword
      - REPMGR_PRIMARY_HOST=pg-0
      - REPMGR_PARTNER_NODES=pg-0,pg-1
      - REPMGR_NODE_NAME=pg-1
      - REPMGR_NODE_NETWORK_NAME=pg-1
    networks:
      - network

  pgpool:
    container_name: pgpool
    build: ./services/pgpool/
    expose:
      - "5432"
    environment:
      - PGPOOL_BACKEND_NODES=0:pg-0:5432,1:pg-1:5432
      - PGPOOL_SR_CHECK_USER=customuser
      - PGPOOL_SR_CHECK_PASSWORD=custompassword
      - PGPOOL_ENABLE_LDAP=no
      - PGPOOL_POSTGRES_USERNAME=customuser
      - PGPOOL_POSTGRES_PASSWORD=custompassword
      - PGPOOL_ADMIN_USERNAME=admin
      - PGPOOL_ADMIN_PASSWORD=custompassword
      - PGPOOL_USER_CONF_FILE=/opt/bitnami/pgpool/conf/transcendence_pgpool.conf
    healthcheck:
      test: ["CMD", "/opt/bitnami/scripts/pgpool/healthcheck.sh"]
      interval: 10s
      timeout: 5s
      retries: 5
    user: root
    networks:
      - network

  user-management:
    container_name: user-management
    build: ./services/user-management/
    expose:
      - "8000"
    volumes:
      - django:/singlepageapp
      - vault-token:/vault/token:ro
      - vault-ssl:/vault/ssl:ro
    networks:
      - network
    depends_on:
      pgpool:
        condition: service_healthy
    env_file:
      - .env
    restart: on-failure

  chat:
    container_name: chat
    build: ./services/chat/
    expose:
      - "8001"
    volumes:
      - django:/singlepageapp/chat
    networks:
      - network
    depends_on:
      - redis
    env_file:
      - .env
    restart: on-failure

  vault:
    build: ./services/vault/
    container_name: vault
    ports:
      - "8200:8200"
    cap_add:
      - IPC_LOCK
    env_file:
      - .env
    networks:
      - network
    healthcheck:
      test: ["CMD", "vault", "status"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
     - vault-data:/vault/data
     - vault-token:/vault/token
     - vault-ssl:/vault/ssl
    hostname: 'vault'
    environment:
      TZ: 'Europe/Paris'
      VAULT_SKIP_IP_AUTO_CONFIG: 'true'
    restart: on-failure

  back-game:
    container_name: back-game-pong
    build: services/back-game-pong/
    expose:
      - "2605"
    env_file: .env
    networks:
     - network
    restart: on-failure

  back-matchmaking:
    container_name: back-matchmaking-pong
    build: services/back-matchmaking-pong/
    expose:
      - "2607"
    env_file: .env
    networks:
      - network
    restart: on-failure

  redis:
    container_name: redis
    build: ./services/redis/
    env_file: .env
    expose:
      - "6379"
    volumes:
      - redis:/var/lib/redis
    networks:
      - network
    restart: on-failure

networks:
  network:
    driver: bridge

volumes:
  nginx:
  django:
  vault-data:
  vault-token:
  vault-ssl:
  redis:
