services:
  postgres:
    container_name: postgres
    image: postgres:16.3
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    ports:
      - '5432:5432'
    networks:
      - network
  django:
    container_name: django
    build: ./containers/django/
    volumes:
      - ./containers/django/app/:/usr/src/app/
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      - postgres
    networks:
      - network
  nginx:
    container_name: nginx
    build: containers/nginx
    ports:
      - "8080:443"
    restart: always
    depends_on:
      - django
    networks:
      - network
volumes:
  postgres_data:

networks:
  network:
    driver: bridge