services:
  front-end:
    container_name: front-end
    build: services/front-end
    ports:
      - "8080:443"
    restart: always
    depends_on:
      - user-management
    volumes:
      - tmp:/singlepageapp
    networks:
      - network

  user-management:
    container_name: user-management
    build: ./services/user-management/
    expose:
      - "8000:8000"
    env_file: .env
    volumes:
      - tmp:/singlepageapp
    networks:
      - network

  postgres:
    env_file: .env
    environment:
      - POSTGRES_USER=${SQL_USER}
      - POSTGRES_DB=${SQL_DATABASE}
      - POSTGRES_PASSWORD=${SQL_PASSWORD}
    #   - "POSTGRES_HOST_AUTH_METHOD=trust"
    container_name: postgres
    image: postgres:16.3
    volumes:
     - ./services/volumes/postgres:/var/lib/postgresql/data/
    networks:
     - network

networks:
  network:
    driver: bridge

volumes:
  tmp:
