services:
  front-end:
    container_name: front-end
    build: services/front-end
    ports:
      - "8080:443"
    restart: always
    depends_on:
      - user-management
    volumes:
      - nginx:/singlepageapp
      - django:/tmp_static/
    networks:
      - network
    entrypoint: sh -c "sh /entrypoint.sh"

  user-management:
    container_name: user-management
    build: ./services/user-management/
    expose:
      - "8000:8000"
    volumes:
      - django:/singlepageapp
    networks:
      - network
    depends_on:
        postgres:
          condition: service_healthy
        vault:
          condition: service_started
    env_file:
      - .env
    environment:
      - VAULT_ADDR=http://vault:8200
      - DJANGO_SUPERUSER_USERNAME=${DJANGO_SUPERUSER_USERNAME}
      - DJANGO_SUPERUSER_PASSWORD=${DJANGO_SUPERUSER_PASSWORD}

  postgres:
    container_name: postgres
    build: ./services/postgres/
    # volumes:
    #   - ./services/volumes/postgres:/var/lib/postgresql/data/
    env_file: .env
    environment:
      - POSTGRES_USER=${SQL_USER}
      - POSTGRES_DB=${SQL_DATABASE}
      - POSTGRES_PASSWORD=${SQL_PASSWORD}
      - VAULT_ADDR=http://vault:8200
    networks:
     - network

  vault:
    build: ./services/vault/
    container_name: vault
    ports:
      - "8200:8200"
    cap_add:
      - IPC_LOCK
    environment:
      - VAULT_ADDR=http://0.0.0.0:8200
    env_file:
      - .env
    networks:
      - network
    depends_on:
      - postgres
  
networks:
  network:
    driver: bridge

volumes:
  nginx:
  django: